---
title: "Example Document to recreate with beamer in Latex"
author: "Thomas Wise"
date: "28/10/2020"
output:
  beamer_presentation:
    theme: "default"
    colortheme: "beaver"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Outline

Working with Equations:

- Aligning the same equations 
- Omitting Equation numbering 
- Ugly Alignment

Discussion

## Working with Equations 

We define a set of equations as 



\begin{equation}
a = b + c^2,
\end{equation}
\begin{equation}
a - c^2 = b,
\end{equation}
\begin{equation}
left side = right side,
\end{equation}
\begin{equation}
left side + something \ge right side
\end{equation}




for all something > 0 

## Aligning the same equations

Aligning the equations by the equal sign gives a much better view into the placements of the separate equation components.

\begin{align}
a &= b + c^2, \\
a - c^2 &= b, \\
left side &= right side, \\
left side + something &\ge right side
\end{align}

## Omit Equation Numbering 

Alternatively the equation numbering can be omitted.

\begin{align*}
a &= b + c^2, \\
a - c^2 &= b, \\
left side &= right side, \\
left side + something &\ge right side
\end{align*}

## Ugly Alignment 

Some components do not look well, when aligned. Especially equations with different heights and spacing. For example:

\begin{align}
E &= mc^2, \\
m &= \frac{E}{c^2}, \\
c &= \sqrt{\frac{E}{m}}
\end{align}

## Discussion

This is where you'd normally give your audience a recap of your talk, where you could discuss e.g. the following 

- Your Main findings, 
- The consequences of your main findings, 
- Things to do, 
- Any other business not currently investiged, but related to your talk. 

