---
title: "R Notebook"
output: html_notebook
---

Loading packages
```{r}
library(tidyverse)
library(knitr)
```

Creating storage for the sampled values
```{r}
samp <- matrix(data = NA, nrow = 1000, ncol = 100)
samp_mean <- rep(NA, 100)
samp_bias <- rep(NA, 100)
ci_low <- rep(NA, 100)
ci_high <- rep(NA, 100)
se <- rep(NA, 100)
```

For loop to draw 100 samples of n=1000
```{r}
set.seed(149)
for (i in 1:100){
  samp[,i] <- rnorm(1000)
  samp_mean[i] <-  mean(samp[,i])
  samp_bias[i] <- abs(samp_mean[i])
  se[i] <- sd(samp[,i])/sqrt(1000)
  ci_high[i] <- samp_mean[i] + qnorm(0.975) * se[i]
  ci_low[i] <-  samp_mean[i] + qnorm(0.025) *se[i]
}
```

Binding results as a dataframe, add variable whether the CI contains the true value and add id
```{r}
estimates <- cbind(samp_mean, samp_bias, se, ci_low, ci_high)
estimates <- as.data.frame(estimates)
estimates$covered <- estimates$ci_low < 0 & estimates$ci_high > 0 
estimates$id <- seq(from = 1, to = 100, by = 1)
```


Plotting 100 sample means with their CI
```{r}
ggplot(data = estimates, mapping = aes(col = covered)) + 
  geom_point(mapping = aes(x = id, y = samp_mean)) +
  geom_errorbar(mapping = aes(x = id, ymin = ci_low, ymax = ci_high)) +
  ylab('Sample means + CI') +
  ggtitle('Sample means with confidence intervals')
```

Table with results of the samples which CI didn't include the true mean.
```{r}
estimates %>%
  filter(!covered) %>%
  knitr::kable(digits = 3)
```

