---
title: "Small Simulation"
author: "Bart-Jan Boverhof"
date: "9/26/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Performing 100 simulation (of cases each 1000 cases) 
```{r}
#Set seed
set.seed(3791)
library(ggplot2)

#Create dataframe to store sampled value's in 
samples <- matrix(nrow = 100,
                  ncol = 1000)

#Create dataframe to store summary stats in
summary <- matrix(nrow = nrow(samples),
                  ncol = 5)
colnames(summary) <- c("absolute bias","se","lower","upper","covered")

#Sample values and attribute to dataframe
for (i in 1:nrow(samples)){
  samples[i,] <- rnorm(ncol(samples))
}

#Calculate sample stats and attribute to summary matrix

for (i in 1:nrow(summary)){
  
  #Absolute bias
  summary[i,1] <- mean(samples[i,])
  
  #Standard error
  summary[i,2] <- (sd(samples[i,])) / sqrt(ncol(samples))
  
  #Lower bound
  summary[i,3] <- sort(samples[i,])[25]
  
  #Upper bound 
  summary[i,4] <- sort(samples[i,])[975]
  
  #Covered?
  summary[i,5] <- summary[i,3] < 0 & 0 < summary[i,4]
} 

#Plot
summary <- data.frame(summary)
ggplot(summary) +
  aes(lower,upper) +
  geom_point(color="blue")+
  xlim(-2.5,0.2)+
  ylim(-0.2,2.5)+
  geom_hline(yintercept = 0, color="red")+
  geom_vline(xintercept = 0, color="red")+
  ggtitle("Scatterplot of Upper bound vs. lower bound")
```
From the plot, it can be discerned that the confidence intervals for all samples include the true sample mean (0). Thus, 100 out of 100 samples cover the mean.
