---
title: "simulation_cassandra"
author: "Cassandra"
date: "17-9-2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```



```{r}
set.seed(666)

```


a. Sample 100 samples from a standard normal distribution
```{r}
num <- 100

#Create a place to store the samples
df <- matrix(0, nrow = 10000, ncol = 100)

#sample with rnorm, repeat 100 times
for (i in 1:num){
  df[,i] <- rnorm(10000, mean = 0, sd = 1)
}

```


b. Sample mean, bias, SE and 95% ci
```{r}

descriptives <- function(data) {
  m <- mean(data) #calculate mean
  bias <- m - 0 #calculate bias
  l <- length(data)
  SE <- 1 / sqrt(l)
  CIlow <- m - (1.96 * SE)
  CIhigh <- m + (1.96 * SE)
return(c(m, bias, SE, CIlow, CIhigh))
}

des <- apply(df, 2, descriptives)

rownames(des) <- c('mean', 'bias' , 'SE', 'CIlow', 'CIhigh')

rowMeans(des)

des <- t(des)

des <- as.data.frame(des)
```

c. Create a plot

First need to create a variable that represents whether the 95% CI covers the population mean

```{r}

des <- des %>%
  mutate(Covered = CIlow < 0 & 0 < CIhigh)

```

Actually create the plot:

```{r}

library(ggplot2)
limits <- aes(ymax = des$CIlow, ymin = des$CIhigh)

ggplot(des, aes(y=des$mean, x=1:100, colour = Covered)) + 
  geom_hline(aes(yintercept = 0), color = "dark grey", size = 2) + 
  geom_pointrange(limits) + 
  xlab("Simulations 1-100") +
  ylab("Means and 95% Confidence Intervals")

```


D. Present table

```{r}

table <- des[!des$Covered, ]

table

```