---
title: "Assignment 1 | Monte Carlo simulation exercise"
author: "Marco Ramljak"
output:  
  html_document:
    code_folding: show
    theme: lumen 
    toc: true  
    toc_float: true
    number_sections: true
---

This small simulation study illustrates the following quote by Neyman in 1934:         
**“A replication of the procedure that generates a 95% confidence interval that is centered around the sample mean would cover the population value at least 95 out of 100 times”**

```{r}
set.seed(378)

library(tidyverse)
library(knitr)
library(kableExtra)
```

# Data creation, function creation and data manipulation
```{r}
# create Matrix with dim 10000 * 100 and transform into list
dat.sim <- replicate(100, 
                     rnorm(n = 10000, mean = 0, sd = 1)) %>% 
  array_tree(margin = 2)

# create function which calculates the mean, the degree of freedom, the standard error, the lower and upper CI bound for a single vector
stat_fun <- function(x) {
  MEAN <- mean(x)
  DF <- length(x) - 1
  SE <- 1 / sqrt(length(x))
  INT <- qt(.975, DF) * SE
  return(c("Mean" = MEAN, "Bias" = MEAN - 0, 
           "SE" = SE, "CI.lower" = MEAN - INT, 
           "CI.upper" = MEAN + INT))
} 

# Executing function on all vectors of the list, bind to one data frame and checking which simulations include the population mean in the CI
results <- dat.sim %>% 
  map_df(stat_fun) %>% 
  mutate(included = case_when(CI.lower < 0 & CI.upper < 0 ~ "Mean not included",
                              TRUE ~ "Mean included"))
```


# Table of simulations which do not include 0 in their 95% CI
```{r}
results %>% 
  filter(included == "Mean not included") %>% 
  kable("html") %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"),
                full_width = F)
```


# Plot
```{r}
results %>% 
  ggplot() +
  geom_hline(yintercept = 0, size = 2, color = "grey") +
  geom_pointrange(aes(x = 1:100, y = Mean, 
                      ymax = CI.upper, ymin = CI.lower,
                      color = included)) +
  labs(x = "Simulation", y = "Means and 95% Confidence Intervals",
       color = "", title = "Visualizing the meaning of confidence intervals",
       subtitle = "Seed = 378, standard normal dist. n = 10.000")
```

