---
title: "Exercise 1"
author: "Yongchao Terry Ma"
date: "9/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Sample 100 samples from a standard normal distribution
```{r}
set.seed(1234)

# 100 samples of 1000 sampled units
N <- 100
sims <- replicate(N, rnorm(5000, 0, 1))
```

## For each of these samples, calculate the following statistics for the mean
```{r}
# mean
mean <- apply(sims, 2, mean)

# absolute bias
bias <- abs(mean - 0)

# standard error
se <- 1/sqrt(5000)

# lower bound of the 95% confidence interval
ci_lower <- mean - qt(.975, 4999)*se

# upper bound of the 95% confidence interval
ci_upper <- mean + qt(.975, 4999)*se
```

## Create a plot
```{r}
# find 5 CIs don't cover the true mean
index <- which(ci_lower > 0 | ci_upper < 0)

# plot all sample means with CI
plot(1:100, mean, ylim = range(c(ci_lower, ci_upper)), pch = 19)
arrows(1:100, ci_lower, 1:100, ci_upper, 
       length = 0.05, angle = 90, code = 3)

# mark 5 CIs as red
arrows(index, ci_lower[index], index, ci_upper[index], 
       length = 0.05, angle = 90, code = 3, col = "red")

# add a line of the true mean
abline(h = 0, lwd = 2, col = "grey")
```

## Present a table containing all simulated samples for which the resulting confidence interval does not contain the population value
```{r}
tbl <- matrix(c(index, mean[index], bias[index], ci_lower[index], ci_upper[index]), 
       nrow = 5)
colnames(tbl) <- c("index", "mean", "bias", "lower", "upper")
tbl
```

